# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Lazy import system tools and CLI."""

from __future__ import annotations


def _get_version() -> str:
    """Get the current version of Exportify.

    Because our version is dynamically generated during build/release, we try several methods to get it. If you downloaded Exportify from PyPi, then the first will work, or the second if the file didn't get generated for some reason. If you're running from source, we try to get the version from git tags. If all else fails, we return "0.0.0".
    """
    try:
        from exportify._version import __version__
    except ImportError:
        try:
            import importlib.metadata

            __version__ = importlib.metadata.version("exportify")
        except importlib.metadata.PackageNotFoundError:
            try:
                import shutil
                import subprocess

                # Try to get version from git if available
                # Git commands work from any directory within a repo, so no need to specify cwd
                # The subprocess call is safe because we use the system to find the executable, not user input
                if git := shutil.which("git"):
                    git_describe = subprocess.run(
                        [git, "describe", "--tags", "--always", "--dirty"],
                        capture_output=True,
                        text=True,
                        check=False,
                    )
                    if git_describe.returncode == 0:
                        __version__ = git_describe.stdout.strip()
                    else:
                        __version__ = "0.0.0"
                else:
                    __version__ = "0.0.0"
            except Exception:
                __version__ = "0.0.0"
    return __version__


__version__ = _get_version()

# === MANAGED EXPORTS ===

# This section is automatically generated by the lazy import system.
# Manual edits below this line will be overwritten.

from types import MappingProxyType
from typing import TYPE_CHECKING

from lateimport import create_late_getattr


if TYPE_CHECKING:
    from exportify.common.types import CallError, ValidationError, ValidationWarning
    from exportify.export_manager.rules import SchemaVersionError

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "CallError": (__spec__.parent, "common.types"),
    "SchemaVersionError": (__spec__.parent, "export_manager.rules"),
    "ValidationError": (__spec__.parent, "common.types"),
    "ValidationWarning": (__spec__.parent, "common.types"),
})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = ("CallError", "SchemaVersionError", "ValidationError", "ValidationWarning")


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
