# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Common utilities for lazy import system."""

from __future__ import annotations


def __getattr__(name: str) -> object:
    if name in _dynamic_imports:
        module_path, attr = _dynamic_imports[name]
        import importlib

        module = importlib.import_module(module_path, package=__name__)
        return getattr(module, attr)
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)


# === MANAGED EXPORTS ===

# This section is automatically generated by the lazy import system.
# Manual edits below this line will be overwritten.

from typing import TYPE_CHECKING
from types import MappingProxyType

from lateimport import create_late_getattr

if TYPE_CHECKING:
    from exportify.common.types import CallError, ValidationError, ValidationWarning

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "CallError": (__spec__.parent, "types"),
    "ValidationError": (__spec__.parent, "types"),
    "ValidationWarning": (__spec__.parent, "types"),
})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = ("CallError", "ValidationError", "ValidationWarning")


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
