# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""File discovery package for lazy import system."""

from __future__ import annotations

from exportify.discovery.file_discovery import FileDiscovery


__all__ = ["FileDiscovery"]

# === MANAGED EXPORTS ===

# This section is automatically generated by the lazy import system.
# Manual edits below this line will be overwritten.

from typing import TYPE_CHECKING
from types import MappingProxyType

from lateimport import create_late_getattr

if TYPE_CHECKING:
    pass

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = ()


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
