# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Export management components.

This package contains the core export management system responsible for
determining which exports should be included in __init__.py files and how
they should propagate through the package hierarchy.

Components:
- RuleEngine: Priority-based rule evaluation
- PropagationGraph: Bottom-up export propagation
- CodeGenerator: __init__.py file generation
"""

from __future__ import annotations

from exportify.export_manager.generator import CodeGenerator, GeneratedCode, validate_init_file
from exportify.export_manager.graph import PropagationGraph
from exportify.export_manager.module_all import (
    ModuleAllFixResult,
    ModuleAllIssue,
    check_module_all,
    fix_module_all,
)
from exportify.export_manager.rules import RuleEngine


__all__ = [
    "CodeGenerator",
    "GeneratedCode",
    "ModuleAllFixResult",
    "ModuleAllIssue",
    "PropagationGraph",
    "RuleEngine",
    "check_module_all",
    "fix_module_all",
    "validate_init_file",
]

# === MANAGED EXPORTS ===

# This section is automatically generated by the lazy import system.
# Manual edits below this line will be overwritten.

from typing import TYPE_CHECKING
from types import MappingProxyType

from lateimport import create_late_getattr

if TYPE_CHECKING:
    from exportify.export_manager.rules import SchemaVersionError

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "SchemaVersionError": (__spec__.parent, "rules")
})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = ("SchemaVersionError",)


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
