#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Code generator for __init__.py files from export manifests.

This module implements the Code Generator component that takes ExportManifest
objects and generates properly formatted __init__.py files with:
- AST-based preservation of manual code (type aliases, imports, functions, etc.)
- Lazy loading via __getattr__ and _dynamic_imports
- Type checking support
- __all__ list generation
- Atomic writes with backup and rollback
"""

from __future__ import annotations

import ast
import hashlib

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Literal

import textcase

from exportify.common.types import ExportManifest, LazyExport
from exportify.export_manager.file_writer import FileWriter, WriteResult
from exportify.export_manager.section_parser import SectionParser


if TYPE_CHECKING:
    from collections.abc import Sequence


# Sentinel comment for managed section
SENTINEL = "# === MANAGED EXPORTS ==="
MANAGED_COMMENT = """# This section is automatically generated by the lazy import system.
# Manual edits below this line will be overwritten."""

# we need to tell REUSE that the following code block is not a license header (it generates them)
# REUSE-IgnoreStart
# SPDX headers for generated files
SPDX_HEADERS = """# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0"""
# REUSE-IgnoreEnd
# Comment markers for preserved sections
PRESERVED_BEGIN = "# --- BEGIN PRESERVED CODE ---"
PRESERVED_END = "# --- END PRESERVED CODE ---"


def _export_sort_key(name: str) -> tuple[Literal[0, 1, 2], str]:
    """Sort key for exports: SCREAMING_SNAKE (0), PascalCase (1), snake_case (2).

    Args:
        name: Export name to classify

    Returns:
        Tuple of (group_number, lowercase_name) for sorting
    """
    if textcase.constant.match(name):
        group = 0  # SCREAMING_SNAKE_CASE
    elif textcase.pascal.match(name):
        group = 1  # PascalCase
    else:
        group = 2  # snake_case
    return (group, name.lower())


@dataclass(frozen=True)
class GeneratedCode:
    """Generated code for a module's __init__.py file."""

    content: str
    manual_section: str
    managed_section: str
    export_count: int
    hash: str

    @classmethod
    def create(
        cls,
        manual: str,
        managed: str,
        export_count: int,
        *,
        include_headers: bool = True,
        add_markers: bool = False,
    ) -> GeneratedCode:
        """Create GeneratedCode with computed hash.

        Args:
            manual: Manual code section to preserve
            managed: Generated managed section
            export_count: Number of exports
            include_headers: Whether to include SPDX headers (default: True)
            add_markers: Whether to add comment markers around preserved code (default: False)
        """
        parts = []

        # Add SPDX headers if requested
        if include_headers:
            parts.append(SPDX_HEADERS)

        # Add manual section if present, positioned between SPDX and SENTINEL
        if manual:
            manual_parts = []
            if add_markers:
                manual_parts.append(PRESERVED_BEGIN)
            manual_parts.append(manual)
            if add_markers:
                manual_parts.append(PRESERVED_END)
            parts.append("\n".join(manual_parts))

        # Add sentinel and managed section
        parts.extend([SENTINEL, MANAGED_COMMENT, "", managed])

        content = "\n\n".join(parts)
        content_hash = hashlib.sha256(content.encode()).hexdigest()

        return cls(
            content=content,
            manual_section=manual,
            managed_section=managed,
            export_count=export_count,
            hash=content_hash,
        )


class CodeGenerator:
    """Generates __init__.py files from export manifests."""

    def __init__(self, output_dir: Path):
        """Initialize code generator."""
        self.output_dir = output_dir
        self.file_writer = FileWriter(validator=self._create_validator())
        self.section_parser = SectionParser()

    def generate(self, manifest: ExportManifest) -> GeneratedCode:
        """Generate code for a single module."""
        # Get target file path
        target = self._get_target_path(manifest.module_path)

        # Preserve manual section if file exists
        manual_section = ""
        if target.exists():
            manual_section = self._preserve_manual_section(target.read_text())

        # Generate managed section
        managed_section = self._generate_managed_section(manifest)

        return GeneratedCode.create(
            manual=manual_section, managed=managed_section, export_count=len(manifest.all_exports)
        )

    def write_file(self, module_path: str, code: GeneratedCode) -> WriteResult:
        """Write generated code to disk (atomic with backup).

        Args:
            module_path: Module path (e.g., 'codeweaver.core.types')
            code: Generated code to write

        Returns:
            WriteResult with success status and paths

        Raises:
            SyntaxError: If generated code has syntax errors
            IOError: If file write fails for other reasons
        """
        target = self._get_target_path(module_path)
        result = self.file_writer.write_file(target, code.content)

        if not result.success:
            # Re-raise syntax errors to match original behavior
            if result.error and "syntax error" in result.error.lower():
                raise SyntaxError(
                    f"❌ Error: Generated code has syntax errors\n\n{result.error}\n\n"
                    "This is a bug in the code generator."
                )
            raise OSError(f"Failed to write {target}: {result.error}")

        return result

    def validate_generated(self, code: GeneratedCode) -> list[str]:
        """Validate generated code (syntax, imports, etc.)."""
        return self._create_validator()(code.content)

    def _create_validator(self):
        """Create validation function for generated code."""

        def validator(content: str) -> list[str]:
            errors = []
            try:
                tree = ast.parse(content)
            except SyntaxError as e:
                errors.append(f"Syntax error at line {e.lineno}: {e.msg}")
                return errors

            has_all = False
            has_dir = False

            for node in ast.walk(tree):
                if isinstance(node, ast.Assign):
                    for target in node.targets:
                        if isinstance(target, ast.Name) and target.id == "__all__":
                            has_all = True
                            break
                elif isinstance(node, ast.FunctionDef) and node.name == "__dir__":
                    has_dir = True

            if not has_all:
                errors.append("Missing __all__ declaration")
            if not has_dir:
                errors.append("Missing __dir__() function")

            return errors

        return validator

    def _preserve_manual_section(self, existing: str) -> str:
        """Extract manual code using AST-based parsing.

        Uses SectionParser to identify and preserve user-defined code sections:
        - Non-TYPE_CHECKING imports
        - Class definitions
        - Function definitions (except __dir__)
        - Variable assignments (except managed ones)
        - Type aliases
        - Constants
        - Comments outside managed sections

        Args:
            existing: Content of existing __init__.py file

        Returns:
            Preserved code section (empty string if nothing to preserve)
        """
        try:
            # Use AST-based parsing to extract preserved sections
            parsed = self.section_parser.parse_file_content(existing)
        except Exception:
            # Fallback to simple sentinel split if AST parsing fails
            # This handles edge cases like syntax errors in existing files
            if SENTINEL not in existing:
                return existing.rstrip()
            return existing.split(SENTINEL)[0].rstrip()
        else:
            return parsed.preserved_code

    def _generate_managed_section(self, manifest: ExportManifest) -> str:
        """Generate the managed section below sentinel."""
        # Sort exports using the custom sort key
        exports = sorted(manifest.all_exports, key=lambda x: _export_sort_key(x.public_name))

        parts = [
            "from __future__ import annotations",
            "",
            "from typing import TYPE_CHECKING",
            "from types import MappingProxyType",
            "",
            "from codeweaver.core.utils.lazy_importer import create_lazy_getattr",
            "",
            "if TYPE_CHECKING:",
        ]
        if exports:
            type_lines = self._generate_type_checking_imports(exports)
            parts.extend([f"    {line}" for line in type_lines])
        else:
            parts.append("    pass")

        # 3. _dynamic_imports dictionary (MappingProxyType wrapper)
        # Only for runtime exports (not type-only)
        runtime_exports = [e for e in exports if not e.is_type_only]

        parts.extend([
            "",
            "_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({",
        ])

        for export in runtime_exports:
            # Extract relative module name from full path
            relative_module = self._extract_relative_module(
                export.target_module, manifest.module_path
            )
            parts.append(f'    "{export.public_name}": (__spec__.parent, "{relative_module}"),')

        parts.append("})")

        parts.extend([
            "",
            "__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)",
            "",
            self._generate_all_tuple(exports),
            "",
            "def __dir__() -> list[str]:",
            '    """List available attributes for the package."""',
            "    return list(__all__)",
        ])
        return "\n".join(parts)

    def _generate_type_checking_imports(self, exports: Sequence[LazyExport]) -> list[str]:
        """Generate import lines for TYPE_CHECKING block, grouped by source module."""
        # Group exports by source module
        by_module: dict[str, list[str]] = {}
        for export in exports:
            if export.target_module not in by_module:
                by_module[export.target_module] = []
            if export.public_name != export.target_object:
                # Aliased import: from mod import obj as alias
                by_module[export.target_module].append(
                    f"{export.target_object} as {export.public_name}"
                )
            else:
                by_module[export.target_module].append(export.public_name)

        # Generate import statements grouped by module
        lines = []
        for module in sorted(by_module.keys()):
            names = sorted(by_module[module], key=_export_sort_key)

            # Multi-line format with trailing comma on last item
            lines.append(f"from {module} import (")
            lines.extend(f"    {name}," for name in names)
            lines.append(")")

        return lines

    def _generate_all_tuple(self, exports: Sequence[LazyExport]) -> str:
        """Generate __all__ tuple (not list)."""
        if not exports:
            return "__all__ = ()"

        names = sorted({e.public_name for e in exports}, key=_export_sort_key)

        if len(names) == 1:
            return f'__all__ = ("{names[0]}",)'

        lines = ["__all__ = ("]
        lines.extend(f'    "{name}",' for name in names)
        lines.append(")")
        return "\n".join(lines)

    def _extract_relative_module(self, target_module: str, package_path: str) -> str:
        """Extract relative module name from full module path.

        Args:
            target_module: Full module path (e.g., 'codeweaver.core.types.models')
            package_path: Package path (e.g., 'codeweaver.core.types')

        Returns:
            Relative module name (e.g., 'models')
        """
        # Remove package prefix to get relative name
        if target_module.startswith(f"{package_path}."):
            return target_module[len(package_path) + 1 :]
        return target_module

    def _get_target_path(self, module_path: str) -> Path:
        """Get target file path for a module."""
        parts = module_path.split(".")
        return self.output_dir / Path(*parts) / "__init__.py"


def _check_ast_declarations(tree: ast.AST) -> tuple[bool, bool]:
    """Check for __all__ and __dir__ in AST."""
    has_all = False
    has_dir = False

    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    has_all = True
        elif isinstance(node, ast.FunctionDef) and node.name == "__dir__":
            has_dir = True

    return has_all, has_dir


def _validate_sentinel_section(content: str) -> list[str]:
    """Validate sentinel and managed section."""
    errors = []
    if SENTINEL not in content:
        return errors

    parts = content.split(SENTINEL)
    if len(parts) != 2:
        errors.append("Multiple sentinels")
    elif "__all__" not in parts[1]:
        errors.append("__all__ not in managed section")

    return errors


def validate_init_file(file_path: Path) -> list[str]:
    """Validate an existing __init__.py file."""
    if not file_path.exists():
        return [f"File does not exist: {file_path}"]
    try:
        content = file_path.read_text()
        tree = ast.parse(content)
    except SyntaxError as e:
        return [f"Syntax error at line {e.lineno}: {e.msg}"]
    except OSError as e:
        return [str(e)]

    errors = []
    has_all, has_dir = _check_ast_declarations(tree)

    if not has_all:
        errors.append("Missing __all__ declaration")
    if not has_dir:
        errors.append("Missing __dir__() function")

    errors.extend(_validate_sentinel_section(content))
    return errors


__all__ = [
    "PRESERVED_BEGIN",
    "PRESERVED_END",
    "SENTINEL",
    "CodeGenerator",
    "GeneratedCode",
    "WriteResult",
    "validate_init_file",
]
