# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

# === MANAGED EXPORTS ===

# This section is automatically generated by the lazy import system.
# Manual edits below this line will be overwritten.
"""This module provides the main command classes for the Exportify CLI."""

from __future__ import annotations

from types import MappingProxyType
from typing import TYPE_CHECKING

from lateimport import create_late_getattr


if TYPE_CHECKING:
    from exportify.commands.check import CheckCommand
    from exportify.commands.clear_cache import ClearCacheCommand
    from exportify.commands.doctor import DoctorCommand
    from exportify.commands.fix import FixCommand
    from exportify.commands.generate import GenerateCommand
    from exportify.commands.init import InitCommand
    from exportify.commands.status import StatusCommand

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "CheckCommand": (__spec__.parent, "check"),
    "ClearCacheCommand": (__spec__.parent, "clear_cache"),
    "DoctorCommand": (__spec__.parent, "doctor"),
    "FixCommand": (__spec__.parent, "fix"),
    "GenerateCommand": (__spec__.parent, "generate"),
    "InitCommand": (__spec__.parent, "init"),
    "StatusCommand": (__spec__.parent, "status"),
})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = (
    "CheckCommand",
    "ClearCacheCommand",
    "DoctorCommand",
    "FixCommand",
    "GenerateCommand",
    "InitCommand",
    "StatusCommand",
)


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
