# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Validator module for lazy imports.

Provides validation of lateimport calls, package consistency, and import resolution.
"""

from __future__ import annotations

from exportify.validator.validator import LateImportValidator


ImportValidator = LateImportValidator


# === MANAGED EXPORTS ===

# This section is automatically generated by exportify.
# Manual edits below this line will be overwritten.

from types import MappingProxyType
from typing import TYPE_CHECKING

from lateimport import create_late_getattr


if TYPE_CHECKING:
    pass

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = ()


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
